# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SideMenuControllerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SideMenuControllerExample
  pod 'JESideMenuController', :path => '../'

end
