language: swift
osx_image: xcode11.3
script:
  - xcodebuild -project JESideMenuController.xcodeproj -scheme JESideMenuController-Package -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
