language: swift
osx_image: xcode11.3
script:
  - xcodebuild test -project JESideMenuController.xcodeproj -scheme JESideMenuController-Package -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11'
after_success:
  - bash <(curl -s https://codecov.io/bash)
