language:
  - swift
osx_image: xcode10.2
script:
  - xcodebuild -project JESideMenuController.xcodeproj -scheme JESideMenuController-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
