name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: macos-26
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.4'

    - name: Build and Test
      run: xcodebuild build test -scheme JESideMenuController -destination "platform=iOS Simulator,name=${SIMULATOR_NAME}" -enableCodeCoverage YES
      env:
        SIMULATOR_NAME: 'iPhone 17'

    - name: Generate code coverage files for codecov
      uses: sersoft-gmbh/swift-coverage-action@v5
      id: coverage-files

    - name: Upload code coverage to codecov.io
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}

  dependabot-auto-merge:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: write
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Approve PR
      run: gh pr review --approve "$PR_URL"

    - name: Enable auto merge
      run: gh pr merge --auto --merge "$PR_URL"
