name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Test
      run: env DEVELOPER_DIR="${XCODE_PATH}" xcrun xcodebuild build test -scheme JESideMenuController -destination "platform=iOS Simulator,name=${SIMULATOR_NAME}" -enableCodeCoverage YES
      env:
        XCODE_PATH: '/Applications/Xcode_16.app'
        SIMULATOR_NAME: 'iPhone SE (3rd generation)'

    - name: Generate code coverage files for codecov
      uses: sersoft-gmbh/swift-coverage-action@v4
      id: coverage-files

    - name: Upload code coverage to codecov.io
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}
